[package]
name = "vox"
version = "0.1.0"
authors = ["jasperdewinther <jasper.dewinther@student.hu.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.27.0"
image = "0.23.8"
rand = "0.7.3"
array-init = "0.1.1"
log = "0.4.11"
fern = "0.6.0"
chrono = "0.4.13"
device_query = "0.2.4"
nalgebra = "0.21.1"
enigo = "0.0.14"
num-traits = "0.2.12"