[package]
name = "vox"
version = "0.0.1"
authors = ["jasperdewinther <jasper.dewinther@student.hu.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.27.0"
image = "0.23.9"
rand = "0.7.3"
array-init = "0.1.1"
log = "0.4.11"
fern = "0.6.0"
chrono = "0.4.15"
device_query = "0.2.5"
nalgebra = "0.22.0"
enigo = "0.0.14"
num-traits = "0.2.12"
noise="0.6.0"
imgui-glium-renderer="0.5.0"
imgui-winit-support = "0.5.0"
flame = "0.2.2"
flamer = "0.3"