[package]
name = "vox"
version = "0.0.1"
authors = ["jasperdewinther <jasper.dewinther@student.hu.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.27"
image = "0.23"
rand = "0.7"
array-init = "0.1"
log = "0.4"
fern = "0.6"
chrono = "0.4"
device_query = "0.2"
nalgebra = "0.22"
enigo = "0.0"
num-traits = "0.2"
noise="0.6"
imgui-glium-renderer="0.5"
imgui-winit-support = "0.5"
rayon = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11"
zstd = "0.5"

[profile.dev]
opt-level = 2