name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install_deps
      run: sudo apt install libxdo-dev
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --release
    - name: Run ray_tracer
      run: cd ray_tracer ; cargo build --release
